Automatically generate the members of each module
CODAIT/pardata pull request #135
Opened 2021-01-07 00:52 UTC by xuhdev

---

## Checklist:

<details open>

<summary></summary>

- Does this pull request close an issue? We encourage you to open an issue first if this pull request (PR) is not a
  minor change.
  - [ ] No
    - [ ] The change in this pull request is minor.
  - [ ] Yes
    - Close #{internal}

For the following questions, only check the boxes that are applicable.

- [ ] Ensure that the pull request text above the horizontal line is descriptive.
- [ ] Add/update relevant tests.
- [ ] Add/update relevant documents.

- Do you have triage permission of this repository?
  - [ ] No
    - You are good.
  - [ ] Yes
    - Does this pull request close an issue?
      - [ ] No, this pull request also acts as an issue by itself.
        - [ ] Assign yourself.
        - [ ] Label this pull request.
        - [ ] Put a milestone.
        - [ ] Put this pull request under "In Progress" or "Under Review" pipeline on ZenHub.
        - [ ] Put this pull request under the appropriate epic on ZenHub.
        - [ ] Put an estimate on ZenHub.
        - [ ] Add dependency relationship with other issues/pull requests on ZenHub.
      - [ ] Yes, this pull request addresses an issue and does not act as an issue.
        - [ ] Connect this pull request to the underlying issue on ZenHub.
        - [ ] DON'T:
          - DON'T assign yourself or anyone else.
          - DON'T label.
          - DON'T put a milestone.
          - DON'T put this pull request under any epic on ZenHub.
          - DON'T put an estimate on ZenHub.
    - [ ] When the pull request is ready, request review.
</details>

2021-01-08 23:22 UTC, edwardleardi requested changes
LGTM, thanks for figuring this out. The sidebar might get a bit messy in case we add more modules structured like `loaders` in the future, but it shouldn't be too big a deal.

2021-01-08 23:22 UTC, edwardleardi commented on docs/source/index.rst
> +API references
```suggestion
API References
```
Heading consistency

2021-01-08 23:22 UTC, edwardleardi commented on docs/source/index.rst
> +   :caption: API references
```suggestion
   :caption: API References
```

2021-01-08 23:22 UTC, edwardleardi commented on docs/source/index.rst
> +   :caption: API references (Loaders)
```suggestion
   :caption: API References (Loaders)
```

2021-01-08 23:38 UTC, xuhdev commented
> LGTM, thanks for figuring this out. The sidebar might get a bit messy in case we add more modules structured like `loaders` in the future, but it shouldn't be too big a deal.

We can always submerge `loaders` when it becomes messy.

2021-01-09 00:26 UTC, edwardleardi approved these changes

2021-01-09 00:26 UTC, merged